### ISSUE TITLE
Add @rgohil bio

### ISSUE THREAD

**Issue by rgohil** [githubteacher/developers-mit#10]
Please add a bio for rgohil and add it to the "/docs" folder
- [x] Your name
- [x] Where you're from
- [x] Favorite food
- [x] Hobby

**Comment by Roachiesmurf** [comment]
# Taking photos?

**Comment by Roachiesmurf** [comment]
# Snarky face?

**Comment by Roachiesmurf** [comment]
# Mine is yelling
