### ISSUE TITLE
Add @ataylor-cs bio to project

### ISSUE THREAD

**Issue by agtaylor-mit** [githubteacher/developers-mit#23]
Please add a bio for @ataylor-cs and add it to the docs folder
- [x] Where you are from
- [x] A favorite food
- [x] A hobby

**Comment by agtaylor-mit** [comment]
## Bio

Where you are from: New Haven, Connecticut 
A Favorite food: Mac & Cheese 
A Hobby: Weightlifting & Fitness

**Comment by agtaylor-mit** [comment]
@githubteacher - Can you add me to the list of users? I don't have the ability to add labels or assign tickets.

**Comment by Roachiesmurf** [comment]
I'm from West Haven!

**Comment by agtaylor-mit** [comment]
I just saw that! CT is in the house!! @Roachiesmurf
